name: market_ledger
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # State Management
  provider: 6.1.5+1
  
  # PDF Generation for printing invoices
  pdf: ^3.10.4
  share_plus: ^7.1.0
  # Date handling
  intl: ^0.19.0
  
  # Local storage for settings
  path_provider: 2.1.5
  shared_preferences: 2.5.3

  http: ^1.1.0  # Ù„Ø¥Ø¬Ø±Ø§Ø¡ Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ø´Ø¨ÙƒØ©

  # Ø§Ù„Ù„ÙˆØºÙˆ
  flutter_launcher_icons: ^0.13.1

   # Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„Ø£Ù…Ø§Ù† ÙˆØ§Ù„Ø­Ù…Ø§ÙŠØ©
  device_info_plus: 10.1.2      # Ø§Ù„Ø­ØµÙˆÙ„ Ø¹Ù„Ù‰ Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø¬Ù‡Ø§Ø²
  crypto: 3.0.6                 # Ø§Ù„ØªØ´ÙÙŠØ± ÙˆØ¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ø¨ØµÙ…Ø§Øª
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Cairo-Regular.ttf

# ðŸ‘‡ Ù‚Ø³Ù… Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚
flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  #adaptive_icon_background: "#FFFFFF"